// import { Roboto } from "@next/font/google"
import Nav from './components/Nav'
import QueryWrapper from './QueryWrapper'
import './globals.css'

// const roboto = Roboto({
//   subsets : ["latin"],
//   weight : ["400","700"],
//   variable: "--font-roboto",
// })

export const metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
  <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-9 bg-sky-600`}>
        <QueryWrapper>
          <Nav/>
          {children}
        </QueryWrapper>
      </body>
  </html>
  )
}
